FROM mcr.microsoft.com/dotnet/sdk:10.0  AS base
USER $APP_UID
EXPOSE 8080
EXPOSE 8081

COPY bin/Release/net10.0/publish/ app/
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
# Provide the cert passphrase at build time, e.g.:
#   docker build -f Dockerfile.local --build-arg CERT_PASSPHRASE=... -t ... .
ARG CERT_PASSPHRASE
RUN test -n "$CERT_PASSPHRASE" && dotnet dev-certs https -v -ep openiddict.pfx -p "$CERT_PASSPHRASE"
RUN chmod 644 openiddict.pfx

FROM base AS final
WORKDIR /app
COPY --from=build /src .

ENTRYPOINT ["dotnet", "Ydls.LuckyLotApi.HttpApi.Host.dll"]